#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

bundle exec jekyll serve &
browse http://localhost:4000/
wait
