name:               "Alex Ford"

url:                "https://asford.info"
author:             "asford"
email:              "a.sewall.ford+github.io@gmail.com"
github:             "asford"
linkedin:           "asewallford"
instagram:          "a.sewall.ford"

background:         "/resources/20160223_102437_E-M5_2230352.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :title/

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Soulful Fibre"
    href:           "/soulful_fibre"
  # - name:           "Scratch"
  #   href:           "/scratch"

collections:
  scratch:
    output: true

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "scratch"
    values:
      layout:       "page"

markdown:           kramdown

sass:
  style:            :compressed

gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
