name:               "Alex Ford"

url:                "http://asford.info"
author:             "asford"
email:              "a.sewall.ford+github.io@gmail.com"
github:             "asford"
linkedin:           "alexander-ford-981b244/"

background:         "/resources/20160223_102437_E-M5_2230352.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
